In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pandas_profiling import ProfileReport
%matplotlib inline
from stop_words import get_stop_words
import nltk
from nltk.corpus import stopwords
from nltk import sent_tokenize, word_tokenize

C:\Users\kishorn\AppData\Local\Continuum\anaconda\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")


#Read the Womens Clothing E-Commerce Reviews.csv file and set it as a Dataframe called clothing_reviews. Check the head, info, and describe methods on the Dataframe

In [2]:
clothing_reviews=pd.read_csv("Womens Clothing E-Commerce Reviews.csv",index_col=False)
column_contain=['Clothing ID','Age','Title','Review Text','Rating','Recommended IND','Positive Feedback Count','Division Name','Department Name','Class Name']

In [3]:
clothing_reviews=pd.DataFrame(data=clothing_reviews,columns=column_contain)
clothing_reviews.head()


Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [4]:
clothing_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Clothing ID              23486 non-null  int64 
 1   Age                      23486 non-null  int64 
 2   Title                    19676 non-null  object
 3   Review Text              22641 non-null  object
 4   Rating                   23486 non-null  int64 
 5   Recommended IND          23486 non-null  int64 
 6   Positive Feedback Count  23486 non-null  int64 
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [5]:
clothing_reviews.describe()

Clothing ID           Age        Rating  Recommended IND  \
count  23486.000000  23486.000000  23486.000000     23486.000000   
mean     918.118709     43.198544      4.196032         0.822362   
std      203.298980     12.279544      1.110031         0.382216   
min        0.000000     18.000000      1.000000         0.000000   
25%      861.000000     34.000000      4.000000         1.000000   
50%      936.000000     41.000000      5.000000         1.000000   
75%     1078.000000     52.000000      5.000000         1.000000   
max     1205.000000     99.000000      5.000000         1.000000   

       Positive Feedback Count  
count             23486.000000  
mean                  2.535936  
std                   5.702202  
min                   0.000000  
25%                   0.000000  
50%                   1.000000  
75%                   3.000000  
max                 122.000000

In [6]:
# Pandas Profiling : Really good library to get the overview EDA.
profile = ProfileReport(clothing_reviews, title='clothing reviews Profiling Report',minimal=False, html={'style':{'full_width':True}})
profile.to_widgets()

In [7]:
# Finding missing values
print(f"Number of Missing values: \n{clothing_reviews.isnull().sum()}\n")

print(f"number of duplicated reviews: {sum(clothing_reviews[clothing_reviews['Review Text'].notnull()].duplicated(['Review Text'],keep='first'))}")

Number of Missing values: 
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

number of duplicated reviews: 7


In [8]:
# Duplicate Review text example
clothing_reviews[clothing_reviews['Review Text'].notnull()][clothing_reviews[clothing_reviews['Review Text'].notnull()].duplicated(['Review Text'],keep=False)]

Clothing ID  Age                                  Title  \
1891          1081   42           Beautiful dress, fits poorly   
7639          1166   26           Love retailer bathing suits!   
9447          1022   37                                    NaN   
10067         1171   26           Love retailer bathing suits!   
10137          872   43                       Love this shirt!   
10708          632   60  Cute cover-up or summer top & shorts!   
11074          628   60  Cute cover-up or summer top & shorts!   
12526         1081   42         Beautiful dress, fits horribly   
13354          393   26           Love retailer bathing suits!   
14275          879   43                        Love this shirt   
16988          993   60                      Soft & beautiful!   
21470          895   60                      Soft & beautiful!   
21888         1022   37                                    NaN   

                                             Review Text  Rating  \
1891   I purchased this and another eva franco dress ...       2   
7639   Perfect fit and i've gotten so many compliment...       5   
9447   Love, love these jeans. being short they come ...       5   
10067  Perfect fit and i've gotten so many compliment...       5   
10137  I bought this shirt at the store and after goi...       5   
10708  Lightweight, soft cotton top and shorts. i thi...       5   
11074  Lightweight, soft cotton top and shorts. i thi...       5   
12526  I purchased this and another eva franco dress ...       2   
13354  Perfect fit and i've gotten so many compliment...       5   
14275  I bought this shirt at the store and after goi...       5   
16988  The sweater and skirt are so pretty! they're r...       5   
21470  The sweater and skirt are so pretty! they're r...       5   
21888  Love, love these jeans. being short they come ...       5   

       Recommended IND  Positive Feedback Count   Division Name  \
1891                 0                        5         General   
7639                 1                        1       Initmates   
9447                 1                        0         General   
10067                1                        0       Initmates   
10137                1                        0  General Petite   
10708                1                        8       Initmates   
11074                1                        2       Initmates   
12526                0                        3         General   
13354                1                        0       Initmates   
14275                1                        0  General Petite   
16988                1                        1         General   
21470                1                        5  General Petite   
21888                1                        0         General   

      Department Name  Class Name  
1891          Dresses     Dresses  
7639         Intimate        Swim  
9447          Bottoms       Jeans  
10067        Intimate        Swim  
10137            Tops       Knits  
10708        Intimate      Lounge  
11074        Intimate      Lounge  
12526         Dresses     Dresses  
13354        Intimate        Swim  
14275            Tops       Knits  
16988         Bottoms      Skirts  
21470            Tops  Fine gauge  
21888         Bottoms       Jeans

#Remove punctuations and stopwords from the text in ‘text’ column

In [9]:
# function to remove all the stopwords and words having lengths less than 3
import re
import string
def cleanDataForME(TextData):
    TextData = re.sub('[^A-Za-z]+', ' ', TextData)    
    word_tokens = word_tokenize(TextData)
    filteredText = ""
    for w in word_tokens:
        if w not in stop_words and len(w) > 2 and not w.isnumeric() and w not in string.punctuation:
            filteredText = filteredText + " " + w
    
    return filteredText.strip()    

In [12]:
nltk.download('stopwords')
nltk.download('punkt')
stop_words = list(get_stop_words('en'))         
nltk_words = list(stopwords.words('english'))   
stop_words.extend(nltk_words)
clothing_reviews['Review Text']=clothing_reviews['Review Text'].astype(str).apply(cleanDataForME)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kishorn\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kishorn\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


#Create two objects X and y. X will be the ' Review Text ' column of clothing_reviews Dataframe and y will be the 'Rating' column. Create a CountVectorizer object and split the data into training and testing sets. Train a MultinomialNB model and Display the confusion Matrix

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
X=clothing_reviews['Review Text']
y=clothing_reviews['Rating']
transformer=CountVectorizer(analyzer='word').fit(X) 
x = transformer.transform(X)
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.4, random_state=101)
nb = MultinomialNB()
nb.fit(x_train, y_train)
predict=nb.predict(x_test)
print(confusion_matrix(y_test, predict))
print('\n')

[[  11   50  171   43   61]
 [   6   34  336  147  122]
 [   6   24  425  359  318]
 [   0    4  175  662 1233]
 [   2   10   50  424 4722]]




#Display the HMM POS tagging on the first 4 rows of ‘Review Text’

In [14]:
nltk.download('averaged_perceptron_tagger')
nltk_data = []
review_data = clothing_reviews.iloc[:4]['Review Text']
for sentence in review_data:
    sentence = nltk.sent_tokenize(sentence)
    for sent in sentence:
        nltk_data.append(nltk.pos_tag(nltk.word_tokenize(sent)))
nltk_data

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\kishorn\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


[[('Absolutely', 'RB'),
  ('wonderful', 'JJ'),
  ('silky', 'JJ'),
  ('sexy', 'NN'),
  ('comfortable', 'JJ')],
 [('Love', 'NNP'),
  ('dress', 'NN'),
  ('sooo', 'NN'),
  ('pretty', 'RB'),
  ('happened', 'VBD'),
  ('find', 'JJ'),
  ('store', 'NN'),
  ('glad', 'NN'),
  ('never', 'RB'),
  ('ordered', 'VBD'),
  ('online', 'JJ'),
  ('petite', 'JJ'),
  ('bought', 'VBD'),
  ('petite', 'JJ'),
  ('love', 'NN'),
  ('length', 'NN'),
  ('hits', 'VBZ'),
  ('little', 'JJ'),
  ('knee', 'JJ'),
  ('definitely', 'RB'),
  ('true', 'JJ'),
  ('midi', 'NN'),
  ('someone', 'NN'),
  ('truly', 'RB'),
  ('petite', 'JJ')],
 [('high', 'JJ'),
  ('hopes', 'NNS'),
  ('dress', 'VBP'),
  ('really', 'RB'),
  ('wanted', 'JJ'),
  ('work', 'NN'),
  ('initially', 'RB'),
  ('ordered', 'VBD'),
  ('petite', 'JJ'),
  ('small', 'JJ'),
  ('usual', 'JJ'),
  ('size', 'NN'),
  ('found', 'VBD'),
  ('outrageously', 'RB'),
  ('small', 'JJ'),
  ('small', 'JJ'),
  ('fact', 'NN'),
  ('zip', 'NN'),
  ('reordered', 'VBD'),
  ('petite', 'JJ')

In [15]:
# Splitting into train and test
import random
random.seed(1234)
train_set, test_set = train_test_split(nltk_data,test_size=0.05)

print(len(train_set))
print(len(test_set))
print(train_set[:5])

3
1
[[('Absolutely', 'RB'), ('wonderful', 'JJ'), ('silky', 'JJ'), ('sexy', 'NN'), ('comfortable', 'JJ')], [('Love', 'NNP'), ('dress', 'NN'), ('sooo', 'NN'), ('pretty', 'RB'), ('happened', 'VBD'), ('find', 'JJ'), ('store', 'NN'), ('glad', 'NN'), ('never', 'RB'), ('ordered', 'VBD'), ('online', 'JJ'), ('petite', 'JJ'), ('bought', 'VBD'), ('petite', 'JJ'), ('love', 'NN'), ('length', 'NN'), ('hits', 'VBZ'), ('little', 'JJ'), ('knee', 'JJ'), ('definitely', 'RB'), ('true', 'JJ'), ('midi', 'NN'), ('someone', 'NN'), ('truly', 'RB'), ('petite', 'JJ')], [('high', 'JJ'), ('hopes', 'NNS'), ('dress', 'VBP'), ('really', 'RB'), ('wanted', 'JJ'), ('work', 'NN'), ('initially', 'RB'), ('ordered', 'VBD'), ('petite', 'JJ'), ('small', 'JJ'), ('usual', 'JJ'), ('size', 'NN'), ('found', 'VBD'), ('outrageously', 'RB'), ('small', 'JJ'), ('small', 'JJ'), ('fact', 'NN'), ('zip', 'NN'), ('reordered', 'VBD'), ('petite', 'JJ'), ('medium', 'NN'), ('overall', 'JJ'), ('top', 'JJ'), ('half', 'NN'), ('comfortable', 'JJ'),

In [16]:
# Getting list of tagged words
train_tagged_words = [tup for sent in train_set for tup in sent]
len(train_tagged_words)

75

In [17]:
# tokens 
tokens = [pair[0] for pair in train_tagged_words]
tokens[:10]

['Absolutely',
 'wonderful',
 'silky',
 'sexy',
 'comfortable',
 'Love',
 'dress',
 'sooo',
 'pretty',
 'happened']

In [18]:
# vocabulary
from nltk.tokenize import word_tokenize
V = set(tokens)
print(len(V))

63


In [19]:
# number of tags
T = set([pair[1] for pair in train_tagged_words])
len(T)

9

In [20]:
print(T)

{'VBP', 'VBD', 'NNP', 'NN', 'VBZ', 'RB', 'IN', 'NNS', 'JJ'}


##  POS Tagging Algorithm - HMM
### Emission Probabilities

In [21]:
# computing P(w/t) and storing in T x V matrix
t = len(T)
v = len(V)
w_given_t = np.zeros((t, v))

In [22]:
# compute word given tag: Emission Probability
def word_given_tag(word, tag, train_bag = train_tagged_words):
    tag_list = [pair for pair in train_bag if pair[1]==tag]
    count_tag = len(tag_list)
    w_given_tag_list = [pair[0] for pair in tag_list if pair[0]==word]
    count_w_given_tag = len(w_given_tag_list)
    
    return (count_w_given_tag, count_tag)

### Transition Probabilities

In [23]:
# compute tag given tag: tag2(t2) given tag1 (t1), i.e. Transition Probability

def t2_given_t1(t2, t1, train_bag = train_tagged_words):
    tags = [pair[1] for pair in train_bag]
    count_t1 = len([t for t in tags if t==t1])
    count_t2_t1 = 0
    for index in range(len(tags)-1):
        if tags[index]==t1 and tags[index+1] == t2:
            count_t2_t1 += 1
    return (count_t2_t1, count_t1)

In [24]:
# creating t x t transition matrix of tags
# each column is t2, each row is t1
# thus M(i, j) represents P(tj given ti)

tags_matrix = np.zeros((len(T), len(T)), dtype='float32')
for i, t1 in enumerate(list(T)):
    for j, t2 in enumerate(list(T)): 
        tags_matrix[i, j] = t2_given_t1(t2, t1)[0]/t2_given_t1(t2, t1)[1]

In [25]:
tags_matrix

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.5       , 0.        , 0.        , 0.5       ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.16666667, 0.        , 0.        , 0.8333333 ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.0952381 , 0.        , 0.42857143, 0.04761905,
        0.23809524, 0.        , 0.        , 0.1904762 ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.27272728, 0.        , 0.        , 0.        ,
        0.        , 0.09090909, 0.        , 0.6363636 ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],


In [26]:
# convert the matrix to a df for better readability
tags_df = pd.DataFrame(tags_matrix, columns = list(T), index=list(T))

In [27]:
tags_df

VBP       VBD       NNP        NN       VBZ        RB        IN  \
VBP  0.0  0.000000  0.000000  0.000000  0.000000  0.500000  0.000000   
VBD  0.0  0.000000  0.000000  0.000000  0.000000  0.166667  0.000000   
NNP  0.0  0.000000  0.000000  1.000000  0.000000  0.000000  0.000000   
NN   0.0  0.095238  0.000000  0.428571  0.047619  0.238095  0.000000   
VBZ  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
RB   0.0  0.272727  0.000000  0.000000  0.000000  0.000000  0.090909   
IN   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
NNS  1.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
JJ   0.0  0.033333  0.033333  0.366667  0.000000  0.100000  0.000000   

          NNS        JJ  
VBP  0.000000  0.500000  
VBD  0.000000  0.833333  
NNP  0.000000  0.000000  
NN   0.000000  0.190476  
VBZ  0.000000  1.000000  
RB   0.000000  0.636364  
IN   0.000000  0.000000  
NNS  0.000000  0.000000  
JJ   0.066667  0.400000

##Parse the first 4 rows of ‘Review Text’ using Viterbi Parser [Use toy_pcfg1 and toy_pcfg2 to get the probabilistic context free grammars; use the PCFG suitable for each sentence] 

In [28]:
import sys, time
from nltk import tokenize
from nltk.parse import ViterbiParser
from nltk.grammar import toy_pcfg1, toy_pcfg2

In [29]:
data = [
        (clothing_reviews.iloc[1]['Review Text'], toy_pcfg1),
        (clothing_reviews.iloc[2]['Review Text'], toy_pcfg2),
    (clothing_reviews.iloc[3]['Review Text'], toy_pcfg1),
    (clothing_reviews.iloc[4]['Review Text'], toy_pcfg2),
    ]

In [30]:
for i in range(len(data)):
    print("%3s: %s" % (i + 1, data[i][0]))
    print("     %r" % data[i][1])
    print()
    sent, grammar = data[i]
    # Tokenize the sentence.
    tokens = sent.split()
    parser = ViterbiParser(grammar)
    all_parses = {}
    parses = all_parses.keys()
    print("\nsent: %s\nparser: %s\ngrammar: %s" % (sent, parser, grammar))

    

  1: Love dress sooo pretty happened find store glad never ordered online petite bought petite love length hits little knee definitely true midi someone truly petite
     <Grammar with 17 productions>


sent: Love dress sooo pretty happened find store glad never ordered online petite bought petite love length hits little knee definitely true midi someone truly petite
parser: <ViterbiParser for <Grammar with 17 productions>>
grammar: Grammar with 17 productions (start state = S)
    S -> NP VP [1.0]
    NP -> Det N [0.5]
    NP -> NP PP [0.25]
    NP -> 'John' [0.1]
    NP -> 'I' [0.15]
    Det -> 'the' [0.8]
    Det -> 'my' [0.2]
    N -> 'man' [0.5]
    N -> 'telescope' [0.5]
    VP -> VP PP [0.1]
    VP -> V NP [0.7]
    VP -> V [0.2]
    V -> 'ate' [0.35]
    V -> 'saw' [0.65]
    PP -> P NP [1.0]
    P -> 'with' [0.61]
    P -> 'under' [0.39]
  2: high hopes dress really wanted work initially ordered petite small usual size found outrageously small small fact zip reordered petite m